package com.telcobright.summary.testkit;

import javax.sql.DataSource;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Logger;

/**
 * The PostgreSQL lab of the integration tests: the throwaway PostgreSQL 16 of {@code tools/lab/pg-lab.sh up}
 * (127.0.0.1:7643, database {@code routesphere}, trust authentication — no password exists). A test makes its
 * tier schemas here the way the real ones are made, acting as each ROLE in turn:
 *
 * <ul>
 *   <li>{@link #provisionTier} — as {@code prime_context}: the schema and its grants, statement for statement what
 *       prime-context's {@code SchemaSharing} runs (R5), with the RULED rights on billing-core's tables
 *       (summary_service gets SELECT by default; DELETE on the outbox is its owner's to give — SS brief N2);</li>
 *   <li>{@link #billingTables} — as {@code billing_core}: its outbox exactly as its
 *       {@code sql/postgres/billing-tables.sql} makes it, and a small {@code cdr}, with its grants;</li>
 *   <li>the service itself runs as {@code summary_service}; ad-sphere's reader as {@code ad_sphere}.</li>
 * </ul>
 *
 * {@code -Dsummary.it.pg.url=…} names another server; {@code -Dsummary.it.pg.prefix=…} another schema prefix (two
 * runs can share one server). Tests SKIP — never pass — when the lab does not answer.
 */
public final class PgLab {

    public static final String URL = System.getProperty("summary.it.pg.url", "jdbc:postgresql://127.0.0.1:7643/routesphere");
    private static final String PREFIX = System.getProperty("summary.it.pg.prefix", "it_");

    public static final String PRIME_CONTEXT = "prime_context";
    public static final String BILLING_CORE = "billing_core";
    public static final String SUMMARY_SERVICE = "summary_service";
    public static final String AD_SPHERE = "ad_sphere";

    private PgLab() {
    }

    /** A schema name of this run: the prefix keeps two runs on one server apart. */
    public static String schema(String name) {
        return PREFIX + name;
    }

    public static boolean reachable() {
        try (Connection c = connect(PRIME_CONTEXT, null)) {
            return true;
        } catch (SQLException e) {
            return false;
        }
    }

    /** A connection as {@code role}; with a schema, that schema is its own (the URL's {@code currentSchema}). */
    public static Connection connect(String role, String schema) throws SQLException {
        return DriverManager.getConnection(urlFor(schema), role, "");
    }

    public static String urlFor(String schema) {
        return schema == null ? URL : URL + (URL.contains("?") ? "&" : "?") + "currentSchema=" + schema;
    }

    /** The datasource a service uses: every connection as {@code role}, opened on {@code schema} (null = none named). */
    public static DataSource dataSource(String role, String schema) {
        return new RoleDataSource(urlFor(schema), role);
    }

    /** As prime-context provisions a tier: the schema anew, the services let in, what they create shared (R5). */
    public static void provisionTier(String schema) {
        run(PRIME_CONTEXT, null,
                "DROP SCHEMA IF EXISTS " + schema + " CASCADE",
                "CREATE SCHEMA " + schema,
                "GRANT USAGE, CREATE ON SCHEMA " + schema + " TO " + AD_SPHERE + ", " + BILLING_CORE + ", " + SUMMARY_SERVICE,
                "ALTER DEFAULT PRIVILEGES FOR ROLE " + BILLING_CORE + " IN SCHEMA " + schema + " GRANT SELECT ON TABLES TO " + AD_SPHERE,
                "ALTER DEFAULT PRIVILEGES FOR ROLE " + SUMMARY_SERVICE + " IN SCHEMA " + schema + " GRANT SELECT ON TABLES TO " + AD_SPHERE,
                "ALTER DEFAULT PRIVILEGES FOR ROLE " + BILLING_CORE + " IN SCHEMA " + schema + " GRANT SELECT ON TABLES TO " + SUMMARY_SERVICE);
    }

    /** Remove a tier schema of this run (a test that makes one at run time cleans up after itself). */
    public static void dropTier(String schema) {
        run(PRIME_CONTEXT, null, "DROP SCHEMA IF EXISTS " + schema + " CASCADE");
    }

    /**
     * As billing-core the first time it serves a schema: {@code summary_affected} as its DDL file makes it (plain,
     * identity cache 1, {@code op} a CHECK), DELETE on it granted to summary_service; and a {@code cdr} cut to the
     * columns a test needs (the real one is partitioned by month — not the summary side's business).
     */
    public static void billingTables(String schema) {
        run(BILLING_CORE, schema,
                "CREATE TABLE summary_affected ("
                        + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "entity_type varchar(32) NOT NULL,"
                        + "op varchar(8) NOT NULL DEFAULT 'add' CHECK (op IN ('add', 'subtract')),"
                        + "data text NOT NULL)",
                "CREATE INDEX ix_summary_affected_entity ON summary_affected (entity_type, id)",
                "GRANT SELECT, DELETE ON summary_affected TO " + SUMMARY_SERVICE,
                "CREATE TABLE cdr (IdCall bigint NOT NULL, ServiceGroup integer NOT NULL, StartTime timestamp NOT NULL, ChannelCallUuid text)",
                "INSERT INTO cdr (IdCall, ServiceGroup, StartTime, ChannelCallUuid) VALUES (1, 30, '2026-10-02 21:14:03', 'a view')");
    }

    /** Run statements as {@code role}, each committed; a failure is the test's failure. */
    public static void run(String role, String schema, String... statements) {
        try (Connection c = connect(role, schema); Statement st = c.createStatement()) {
            for (String sql : statements) {
                st.execute(sql);
            }
        } catch (SQLException e) {
            throw new IllegalStateException("as " + role + (schema == null ? "" : " in " + schema) + ": " + e.getMessage(), e);
        }
    }

    public static long queryLong(String role, String schema, String sql) {
        try (Connection c = connect(role, schema); Statement st = c.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            rs.next();
            return rs.getLong(1);
        } catch (SQLException e) {
            throw new IllegalStateException("as " + role + ": " + sql + " — " + e.getMessage(), e);
        }
    }

    public static String queryText(String role, String schema, String sql) {
        try (Connection c = connect(role, schema); Statement st = c.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            return rs.next() ? rs.getString(1) : null;
        } catch (SQLException e) {
            throw new IllegalStateException("as " + role + ": " + sql + " — " + e.getMessage(), e);
        }
    }

    /** The error a statement gives as {@code role}, or null when it runs. */
    public static String refusal(String role, String schema, String sql) {
        try (Connection c = connect(role, schema); Statement st = c.createStatement()) {
            st.execute(sql);
            return null;
        } catch (SQLException e) {
            return e.getMessage();
        }
    }

    /** Minimal DataSource over DriverManager: every connection as one role (trust: no password). */
    private record RoleDataSource(String url, String role) implements DataSource {
        @Override
        public Connection getConnection() throws SQLException {
            return DriverManager.getConnection(url, role, "");
        }

        @Override
        public Connection getConnection(String username, String password) throws SQLException {
            return DriverManager.getConnection(url, username, password);
        }

        @Override
        public PrintWriter getLogWriter() {
            return null;
        }

        @Override
        public void setLogWriter(PrintWriter out) {
        }

        @Override
        public void setLoginTimeout(int seconds) {
        }

        @Override
        public int getLoginTimeout() {
            return 0;
        }

        @Override
        public Logger getParentLogger() {
            return Logger.getGlobal();
        }

        @Override
        public <T> T unwrap(Class<T> iface) {
            throw new UnsupportedOperationException();
        }

        @Override
        public boolean isWrapperFor(Class<?> iface) {
            return false;
        }
    }
}
