#!/usr/bin/env bash
# The store goes away for a while and comes back — brief S16, with the PACKAGED jar. A worker whose store went away
# comes back by itself when the store is back, with no restart, and says so ONCE each way.
#
#   tools/lab/outage-e2e.sh [pg | mysql | both]     (default both)
#
# For each engine, on this box only (tools/lab/pg-lab.sh: PostgreSQL 16 on 127.0.0.1:7643, MySQL 5.7.44 on
# 127.0.0.1:7633, Kafka on 127.0.0.1:7692), with a schema / database of its own:
#   1. the service serves it (one tenant; the poll is the default 5 s); billing-core's rows are written and summed
#   2. a backlog of outbox rows is written and, while the service drains it, the database's container is STOPPED
#      for OUTAGE_SECONDS (default 40) — the database restarts, every connection the pool held is dead
#   3. the database is started again; more rows are written (billing-core recovering)
#   4. every row is summed within a minute of the database answering again — the service is NOT restarted — and
#      what it said: how many ERROR and INFO lines its workers wrote about the outage
# The service is started by tools/lab/run-lab.sh (the endpoints shown first; every host this box). What the story
# makes is removed at the end; the containers stay (tools/lab/pg-lab.sh down removes them).
set -euo pipefail
cd "$(dirname "$0")/../.."

ENGINES=${1:-both}
OUTAGE_SECONDS=${OUTAGE_SECONDS:-40}
BACKLOG=${BACKLOG:-3000}
PG=ss-pg16-lab; MY=ss-mysql57-lab
SCHEMA=lab_outage
WORK=target/lab-e2e; JAR=target/quarkus-app/quarkus-run.jar
mkdir -p "$WORK"
[ -f "$JAR" ] || { echo "no packaged application — run: mvn package -DskipTests"; exit 2; }

say() { printf '\n== %s ==\n' "$*"; }
service_pid=""
stop_service() { [ -n "$service_pid" ] && kill "$service_pid" 2>/dev/null || true; service_pid=""; sleep 2; }
pg()  { local role=$1; shift; docker exec -i "$PG" psql -U "$role" -d routesphere -q -v ON_ERROR_STOP=1 "$@"; }
pgv() { docker exec -i "$PG" psql -U "$1" -d routesphere -tA -c "$2" 2>/dev/null; }
my()  { docker exec -i "$MY" mysql -uroot -N "$@"; }
myv() { docker exec -i "$MY" mysql -uroot -N -e "$1" 2>/dev/null; }
cleanup() {
  stop_service
  docker start "$PG" >/dev/null 2>&1 || true; docker start "$MY" >/dev/null 2>&1 || true
  for _ in $(seq 1 60); do docker exec "$PG" pg_isready -U postgres >/dev/null 2>&1 && break; sleep 1; done
  pg postgres -c "DROP SCHEMA IF EXISTS $SCHEMA CASCADE" >/dev/null 2>&1 || true
  for _ in $(seq 1 60); do myv "select 1" >/dev/null && break; sleep 1; done
  myv "DROP DATABASE IF EXISTS $SCHEMA" >/dev/null || true
}
trap cleanup EXIT
tools/lab/pg-lab.sh all >/dev/null
cleanup

[ -s "$WORK/cp.txt" ] || mvn -o -q dependency:build-classpath -Dmdep.outputFile="$WORK/cp.txt" -Dmdep.includeScope=test >/dev/null
ROW=$(java -cp "target/classes:target/test-classes:$(cat "$WORK/cp.txt")" com.telcobright.summary.testkit.LabOutboxRow 2>/dev/null)   # ONE ad view, as billing-core writes it

# ---- one engine's story -------------------------------------------------------------------------------------------
# $1 = pg | mysql. The functions below differ per engine; the story is one.
setup_pg() {
  pg prime_context -c "CREATE SCHEMA $SCHEMA" -c "GRANT USAGE, CREATE ON SCHEMA $SCHEMA TO summary_service, billing_core" \
     -c "ALTER DEFAULT PRIVILEGES FOR ROLE summary_service IN SCHEMA $SCHEMA GRANT SELECT ON TABLES TO ad_sphere" >/dev/null 2>&1
  pg billing_core <<SQL
SET search_path TO $SCHEMA;
CREATE TABLE summary_affected (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, entity_type varchar(32) NOT NULL,
  op varchar(8) NOT NULL DEFAULT 'add' CHECK (op IN ('add', 'subtract')), data text NOT NULL);
GRANT SELECT, DELETE ON summary_affected TO summary_service;
SQL
  OPTIONS=(-Dsummary.tenants.mode=single "-Dsummary.store.url=jdbc:postgresql://127.0.0.1:7643/routesphere?currentSchema=$SCHEMA")
}
setup_mysql() {
  myv "CREATE DATABASE $SCHEMA" >/dev/null
  # the lab's partition horizon (the views are of 2026-10-02): six tables of 731 daily partitions each take minutes on a busy box
  OPTIONS=(-Dsummary.tenants.mode=single -Dsummary.store.kind=mysql -Dsummary.store.username=root
           -Dsummary.ddl.partition-start=2026-09-01 -Dsummary.ddl.partition-days=60
           "-Dsummary.store.url=jdbc:mysql://127.0.0.1:7633/$SCHEMA?useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true")
}
write_rows() {   # $1 = engine, $2 = how many outbox rows (one view each), in one statement
  if [ "$1" = pg ]; then
    pgv billing_core "INSERT INTO $SCHEMA.summary_affected (entity_type, op, data) SELECT 'cdr', 'add', '$ROW' FROM generate_series(1, $2)" >/dev/null
  else
    myv "INSERT INTO $SCHEMA.summary_affected (entity_type, op, data) SELECT 'cdr', 'add', '$ROW' FROM (SELECT 1 FROM information_schema.columns a, information_schema.columns b LIMIT $2) n" >/dev/null
  fi
}
views()   { if [ "$1" = pg ]; then pgv summary_service "select coalesce(sum(views),0) from $SCHEMA.sum_ad_day_30"; else myv "select coalesce(sum(views),0) from $SCHEMA.sum_ad_day_30"; fi; }
written() { if [ "$1" = pg ]; then pgv billing_core "select coalesce(max(id),0) from $SCHEMA.summary_affected"; else myv "select coalesce(max(id),0) from $SCHEMA.summary_affected"; fi; }
caughtUp() {   # how many of the six beans have their bookmark at the last outbox row ($2)
  if [ "$1" = pg ]; then pgv summary_service "select count(*) from $SCHEMA.summary_offset where last_offset >= $2"; else myv "select count(*) from $SCHEMA.summary_offset where last_offset >= $2"; fi
}
answers() { if [ "$1" = pg ]; then docker exec "$PG" pg_isready -U postgres >/dev/null 2>&1 && [ "$(pgv summary_service "select 1")" = "1" ]; else [ "$(myv "select 1")" = "1" ]; fi; }

story() {
  local engine=$1 container log
  container=$([ "$engine" = pg ] && echo "$PG" || echo "$MY")
  log="$WORK/outage-$engine.log"
  say "$engine · 1 · the service serves $SCHEMA; billing-core's first rows are summed"
  "setup_$engine"
  tools/lab/run-lab.sh btcl/lab "${OPTIONS[@]}" > "$log" 2>&1 &
  service_pid=$!
  for _ in $(seq 1 480); do grep -q "is served: 6 of 6\|NOT STARTED\|REFUSING" "$log" && break; sleep 0.5; done
  grep -q "is served: 6 of 6" "$log" || { echo "not served:"; grep -E "ERROR|REFUS|NOT STARTED" "$log" | tail -8 | cut -c1-260; exit 1; }
  if [ "$engine" = mysql ]; then for _ in $(seq 1 60); do [ -n "$(myv "show tables in $SCHEMA like 'summary_affected'")" ] && break; sleep 0.5; done; fi
  write_rows "$engine" 20
  for _ in $(seq 1 120); do [ "$(views "$engine")" = "20" ] && break; sleep 0.5; done
  echo "views summed: $(views "$engine") of 20"
  [ "$(views "$engine")" = "20" ] || { echo "FAILED: the first rows were not summed"; exit 1; }

  say "$engine · 2 · a backlog of $BACKLOG rows; while it is drained, the database is STOPPED for ${OUTAGE_SECONDS} s"
  write_rows "$engine" "$BACKLOG"
  for _ in $(seq 1 200); do [ "$(views "$engine")" -gt 40 ] 2>/dev/null && break; sleep 0.05; done
  echo "draining: $(views "$engine") views summed when the database stops"
  local stopped_at; stopped_at=$(date +%s)
  docker stop -t 2 "$container" >/dev/null
  echo "stopped at $(date +%T)"
  sleep "$OUTAGE_SECONDS"
  docker start "$container" >/dev/null
  for _ in $(seq 1 120); do answers "$engine" && break; sleep 0.5; done
  answers "$engine" || { echo "FAILED: the database did not come back"; exit 1; }
  local back_at; back_at=$(date +%s)
  echo "the database answers again at $(date +%T) ($((back_at - stopped_at)) s after it stopped); the service was NOT restarted (pid $service_pid)"

  say "$engine · 3 · billing-core writes more rows; every row must be summed within a minute"
  write_rows "$engine" 50
  local want; want=$(written "$engine")
  local first_at="" done_at="" before; before=$(views "$engine")
  for _ in $(seq 1 600); do
    [ -z "$first_at" ] && grep -q "writes again —" "$log" && first_at=$(date +%s)
    [ "$(views "$engine")" = "$want" ] && [ "$(caughtUp "$engine" "$want")" = "6" ] && { done_at=$(date +%s); break; }
    [ $(( $(date +%s) - back_at )) -gt 90 ] && break
    sleep 0.2
  done
  echo "the first worker wrote again $([ -n "$first_at" ] && echo "$((first_at - back_at)) s" || echo "NEVER") after the database's return"
  echo "outbox rows written: $want; views summed: $(views "$engine"); beans caught up: $(caughtUp "$engine" "$want") of 6$([ -n "$done_at" ] && echo " — every row by every bean, $((done_at - back_at)) s after the database's return")"

  say "$engine · 4 · what the workers said about it"
  local errors infos
  errors=$(grep -c "ERROR.*OutboxWorker\|ERROR.*\[com.tel.sum.reg.int.OutboxWorker\]" "$log" || true)
  infos=$(grep -c "INFO.*\[com.tel.sum.reg.int.OutboxWorker\].*writes again" "$log" || true)
  echo "ERROR lines of the workers: $errors   INFO lines 'writes again': $infos   (6 workers)"
  grep -E "\[com.tel.sum.reg.int.OutboxWorker\]" "$log" | grep -E "ERROR|writes again" | cut -c1-230 | head -4
  echo "   …"
  stop_service
  [ -n "$done_at" ] && [ $((done_at - back_at)) -le 60 ] || { echo "FAILED ($engine): the rows were NOT all summed within a minute of the database's return — the service is stuck (log: $log)"; return 1; }
  [ "$errors" -le 6 ] && [ "$infos" = "6" ] || { echo "FAILED ($engine): one ERROR and one INFO per worker was wanted (log: $log)"; return 1; }
  echo "$engine HOLDS: back by itself, every row summed, one ERROR and one INFO per worker"
}

result=0
case "$ENGINES" in
  pg)    story pg || result=1 ;;
  mysql) story mysql || result=1 ;;
  both)  story pg || result=1; cleanup; story mysql || result=1 ;;
  *)     echo "usage: $0 [pg | mysql | both]"; exit 2 ;;
esac
echo; [ "$result" = 0 ] && echo "S16 HOLDS: the store went away and came back; the service came back by itself, with no restart." || echo "S16 DOES NOT HOLD — see above."
echo "removing: the service, the schema / database (the containers stay)"
exit "$result"
