#!/usr/bin/env bash
# The store ends every session and comes back — S16 (the second rehearsal's F8), with the PACKAGED jar, on BOTH engines,
# THREE ways each. The rule: after the database closed every connection the summaries catch up with NO restart of this
# service — the first drain after the database is back writes, no bean stays STUCK, a schema the watcher could not serve
# is served again, the ERROR lines stop.
#
#   tools/lab/outage-e2e.sh [pg | mysql | both]     (default both)
#
# For each engine, on this box only (tools/lab/pg-lab.sh: PostgreSQL 16 on 127.0.0.1:7643, MySQL 5.7.44 on 127.0.0.1:7633,
# Kafka on 127.0.0.1:7692), with a schema / database of its own that holds a `cdr` table and billing-core's outbox —
# every view written is ONE cdr row and ONE outbox row in the same transaction, so "the summaries equal the cdr rows"
# is read literally: count(cdr) = sum(views) of sum_ad_day_30 = of sum_ad_hr_30, and all six beans at the last row.
#   1. the service serves it (one tenant; the poll is the profile's 5 s); the first rows are summed
#   2. (a) the service's SESSIONS are ENDED by the server under traffic — pg_terminate_backend / KILL — twice; more traffic;
#          every row summed within 30 s; the service was not restarted
#   3. (b) a backlog of BACKLOG rows and, mid-drain, the database's container is STOPPED for OUTAGE_SECONDS (default 40)
#          and started again (every connection the pool held is dead); more traffic; every row summed within 60 s of the
#          database's return; the service was not restarted
#   4. the ERROR lines STOP: none in the 15 s after the sums are equal; what the workers said (ERROR once per trouble,
#          INFO once when they write again)
#   5. (c) the service is STARTED while the database is DOWN: "could NOT be served" once; the database starts; the schema
#          is served by the watcher's retry with no restart; traffic; every row summed
# The service is started by tools/lab/run-lab.sh (the endpoints shown first; every host this box). What the story makes
# is removed at the end; the containers stay (tools/lab/pg-lab.sh down removes them). Maven reads MAVEN_ARGS (the private
# repository's flags) when it has to build the classpath of the row tool.
set -euo pipefail
cd "$(dirname "$0")/../.."

ENGINES=${1:-both}
OUTAGE_SECONDS=${OUTAGE_SECONDS:-40}
BACKLOG=${BACKLOG:-3000}
PG=ss-pg16-lab; MY=ss-mysql57-lab
SCHEMA=lab_outage
WORK=target/lab-e2e; JAR=target/quarkus-app/quarkus-run.jar
mkdir -p "$WORK"
[ -f "$JAR" ] || { echo "no packaged application — run: mvn package -DskipTests"; exit 2; }

say() { printf '\n== %s ==\n' "$*"; }
service_pid=""
stop_service() { [ -n "$service_pid" ] && kill "$service_pid" 2>/dev/null || true; service_pid=""; sleep 2; }
pg()  { local role=$1; shift; docker exec -i "$PG" psql -U "$role" -d routesphere -q -v ON_ERROR_STOP=1 "$@"; }
pgv() { docker exec -i "$PG" psql -U "$1" -d routesphere -tA -c "$2" 2>/dev/null; }
my()  { docker exec -i "$MY" mysql -uroot -N "$@"; }
myv() { docker exec -i "$MY" mysql -uroot -N -e "$1" 2>/dev/null; }
cleanup() {
  stop_service
  docker start "$PG" >/dev/null 2>&1 || true; docker start "$MY" >/dev/null 2>&1 || true
  for _ in $(seq 1 60); do docker exec "$PG" pg_isready -U postgres >/dev/null 2>&1 && break; sleep 1; done
  pg postgres -c "DROP SCHEMA IF EXISTS $SCHEMA CASCADE" >/dev/null 2>&1 || true
  for _ in $(seq 1 90); do myv "select 1" >/dev/null && break; sleep 1; done
  myv "DROP DATABASE IF EXISTS $SCHEMA" >/dev/null || true
}
trap cleanup EXIT
tools/lab/pg-lab.sh all >/dev/null
cleanup

[ -s "$WORK/cp.txt" ] || mvn -o -q dependency:build-classpath -Dmdep.outputFile="$WORK/cp.txt" -Dmdep.includeScope=test >/dev/null
ROW=$(java -cp "target/classes:target/test-classes:$(cat "$WORK/cp.txt")" com.telcobright.summary.testkit.LabOutboxRow 2>/dev/null)   # ONE ad view, as billing-core writes it

# ---- one engine's story -------------------------------------------------------------------------------------------
# $1 = pg | mysql. The functions below differ per engine; the story is one.
setup_pg() {
  pg prime_context -c "CREATE SCHEMA $SCHEMA" -c "GRANT USAGE, CREATE ON SCHEMA $SCHEMA TO summary_service, billing_core" \
     -c "ALTER DEFAULT PRIVILEGES FOR ROLE summary_service IN SCHEMA $SCHEMA GRANT SELECT ON TABLES TO ad_sphere" >/dev/null 2>&1
  pg billing_core <<SQL
SET search_path TO $SCHEMA;
CREATE TABLE cdr (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE summary_affected (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, entity_type varchar(32) NOT NULL,
  op varchar(8) NOT NULL DEFAULT 'add' CHECK (op IN ('add', 'subtract')), data text NOT NULL);
GRANT SELECT, DELETE ON summary_affected TO summary_service;
SQL
  OPTIONS=(-Dsummary.tenants.mode=single "-Dsummary.store.url=jdbc:postgresql://127.0.0.1:7643/routesphere?currentSchema=$SCHEMA")
}
setup_mysql() {
  myv "CREATE DATABASE $SCHEMA" >/dev/null
  myv "CREATE TABLE $SCHEMA.cdr (id bigint AUTO_INCREMENT PRIMARY KEY)" >/dev/null
  # the lab's partition horizon (the views are of 2026-10-02): six tables of 731 daily partitions each take minutes on a busy box
  OPTIONS=(-Dsummary.tenants.mode=single -Dsummary.store.kind=mysql -Dsummary.store.username=root
           -Dsummary.ddl.partition-start=2026-09-01 -Dsummary.ddl.partition-days=60
           "-Dsummary.store.url=jdbc:mysql://127.0.0.1:7633/$SCHEMA?useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true")
}
write_rows() {   # $1 = engine, $2 = how many views: ONE cdr row and ONE outbox row each, in ONE transaction (as billing-core writes)
  if [ "$1" = pg ]; then
    pgv billing_core "INSERT INTO $SCHEMA.cdr SELECT FROM generate_series(1, $2); INSERT INTO $SCHEMA.summary_affected (entity_type, op, data) SELECT 'cdr', 'add', '$ROW' FROM generate_series(1, $2)" >/dev/null
  else
    myv "START TRANSACTION; INSERT INTO $SCHEMA.cdr () SELECT NULL FROM (SELECT 1 FROM information_schema.columns a, information_schema.columns b LIMIT $2) n; INSERT INTO $SCHEMA.summary_affected (entity_type, op, data) SELECT 'cdr', 'add', '$ROW' FROM (SELECT 1 FROM information_schema.columns a, information_schema.columns b LIMIT $2) n; COMMIT" >/dev/null
  fi
}
q() { if [ "$1" = pg ]; then pgv postgres "$2"; else myv "$2"; fi; }     # a read as the lab's superuser
cdrRows()  { q "$1" "select count(*) from $SCHEMA.cdr"; }
dayViews() { q "$1" "select coalesce(sum(views),0) from $SCHEMA.sum_ad_day_30"; }
hrViews()  { q "$1" "select coalesce(sum(views),0) from $SCHEMA.sum_ad_hr_30"; }
written()  { q "$1" "select coalesce(max(id),0) from $SCHEMA.summary_affected"; }
caughtUp() { q "$1" "select count(*) from $SCHEMA.summary_offset where last_offset >= $2"; }   # how many of the six beans are at the last outbox row
sessions() { if [ "$1" = pg ]; then pgv postgres "select count(*) from pg_stat_activity where usename = 'summary_service'"; else myv "select count(*) from information_schema.processlist where id <> connection_id() and db = '$SCHEMA'"; fi; }
endSessions() {   # the server ends every session of the service — what a restart does to them; how many
  if [ "$1" = pg ]; then pgv postgres "select count(pg_terminate_backend(pid)) from pg_stat_activity where usename = 'summary_service' and pid <> pg_backend_pid()"
  else local kills; kills=$(myv "select ifnull(group_concat(concat('KILL ', id, ';') separator ' '), '') from information_schema.processlist where id <> connection_id() and db = '$SCHEMA'")
       [ -n "$kills" ] && myv "$kills" >/dev/null; echo "$kills" | grep -o "KILL" | wc -l; fi
}
answers() { if [ "$1" = pg ]; then docker exec "$PG" pg_isready -U postgres >/dev/null 2>&1 && [ "$(pgv summary_service "select 1")" = "1" ]; else [ "$(myv "select 1")" = "1" ]; fi; }
equal() {   # $1 engine: every summary equals the cdr rows and every bean is at the last outbox row
  local rows; rows=$(cdrRows "$1"); local last; last=$(written "$1")
  [ "$(dayViews "$1")" = "$rows" ] && [ "$(hrViews "$1")" = "$rows" ] && [ "$(caughtUp "$1" "$last")" = "6" ]
}
waitEqual() {   # $1 engine, $2 seconds at most; prints how long it took; false when not within it
  local started; started=$(date +%s)
  for _ in $(seq 1 $(( $2 * 5 ))); do
    if equal "$1"; then echo "$(( $(date +%s) - started )) s: cdr $(cdrRows "$1") = sum_ad_day_30 $(dayViews "$1") = sum_ad_hr_30 $(hrViews "$1"), 6 of 6 beans at row $(written "$1")"; return 0; fi
    sleep 0.2
  done
  echo "NOT EQUAL after $2 s: cdr $(cdrRows "$1"), sum_ad_day_30 $(dayViews "$1"), sum_ad_hr_30 $(hrViews "$1"), beans at the last row: $(caughtUp "$1" "$(written "$1")") of 6"; return 1
}
errorLines() { grep -c " ERROR " "$1" || true; }
start_service() {   # $1 engine, $2 log; waits for the start's verdict
  tools/lab/run-lab.sh btcl/lab "${OPTIONS[@]}" > "$2" 2>&1 &
  service_pid=$!
  for _ in $(seq 1 480); do grep -q "is served: 6 of 6\|could NOT be served\|NOT STARTED\|REFUSING" "$2" && break; sleep 0.5; done
}

story() {
  local engine=$1 container log
  container=$([ "$engine" = pg ] && echo "$PG" || echo "$MY")
  log="$WORK/outage-$engine.log"
  local verdict=0

  say "$engine · 1 · the service serves $SCHEMA; the first rows are summed"
  "setup_$engine"
  start_service "$engine" "$log"
  grep -q "is served: 6 of 6" "$log" || { echo "not served:"; grep -E "ERROR|REFUS|NOT STARTED" "$log" | tail -8 | cut -c1-260; return 1; }
  grep "store: " "$log" | sed 's/.*store: /the store: /' | cut -c1-230
  if [ "$engine" = mysql ]; then for _ in $(seq 1 60); do [ -n "$(myv "show tables in $SCHEMA like 'summary_affected'")" ] && break; sleep 0.5; done; fi
  write_rows "$engine" 20
  waitEqual "$engine" 60 || return 1

  say "$engine · 2 · (a) the server ENDS the service's sessions under traffic — twice; the service is not restarted (pid $service_pid)"
  write_rows "$engine" 300
  for _ in $(seq 1 100); do [ "$(dayViews "$engine")" -gt 40 ] 2>/dev/null && break; sleep 0.05; done
  echo "draining: $(dayViews "$engine") views summed, $(sessions "$engine") session(s) of the service"
  echo "ended by the server: $(endSessions "$engine") session(s) at $(date +%T)"; sleep 1.5
  echo "ended by the server: $(endSessions "$engine") session(s) at $(date +%T) (again)"
  write_rows "$engine" 50
  local errorsA; errorsA=$(errorLines "$log")
  waitEqual "$engine" 30 || verdict=1
  echo "sessions of the service now: $(sessions "$engine") (new ones; the ended ones were dropped); ERROR lines so far: $errorsA"

  say "$engine · 3 · (b) a backlog of $BACKLOG rows; mid-drain the database is STOPPED for ${OUTAGE_SECONDS} s and started again"
  local before; before=$(dayViews "$engine")
  write_rows "$engine" "$BACKLOG"
  for _ in $(seq 1 200); do [ "$(dayViews "$engine")" -gt $((before + 40)) ] 2>/dev/null && break; sleep 0.05; done
  echo "draining: $(dayViews "$engine") views summed when the database stops"
  local stopped_at; stopped_at=$(date +%s)
  docker stop -t 10 "$container" >/dev/null
  echo "stopped at $(date +%T)"
  sleep "$OUTAGE_SECONDS"
  docker start "$container" >/dev/null
  for _ in $(seq 1 180); do answers "$engine" && break; sleep 0.5; done
  answers "$engine" || { echo "FAILED: the database did not come back"; return 1; }
  local back_at; back_at=$(date +%s)
  echo "the database answers again at $(date +%T) ($((back_at - stopped_at)) s after it stopped); the service was NOT restarted (pid $service_pid)"
  write_rows "$engine" 50
  waitEqual "$engine" 60 || verdict=1
  local first; first=$(grep -m1 "writes again —" "$log" | awk '{print $2}' | cut -d, -f1 || true)
  echo "the first worker wrote again at ${first:-NEVER} (the database was back at $(date -d "@$back_at" +%T))"

  say "$engine · 4 · the ERROR lines stop; what the workers said"
  local errorsNow; errorsNow=$(errorLines "$log")
  sleep 15
  local errorsThen; errorsThen=$(errorLines "$log")
  echo "ERROR lines: $errorsNow when the sums were equal, $errorsThen 15 s later$([ "$errorsThen" = "$errorsNow" ] && echo " — they stopped" || echo " — STILL COMING")"
  [ "$errorsThen" = "$errorsNow" ] || verdict=1
  local workerErrors infos
  workerErrors=$(grep -c "ERROR.*OutboxWorker\]" "$log" || true); infos=$(grep -c "writes again —" "$log" || true)
  echo "the workers (6): $workerErrors ERROR line(s) over the three troubles (at most one per worker per trouble = 18), $infos 'writes again' INFO line(s) (one per ERROR)"
  [ "$workerErrors" -le 18 ] && [ "$infos" = "$workerErrors" ] || verdict=1
  grep -E "OutboxWorker\]" "$log" | grep -E " ERROR | INFO .*writes again" | sed 's/^\([^ ]*\) .* \(ERROR\|INFO\) .*OutboxWorker\] (\([^)]*\)) \(.*\)$/\1 \2 (\3) \4/' | cut -c1-200 | head -6
  echo "   …"
  stop_service

  say "$engine · 5 · (c) the service is STARTED while the database is DOWN; the schema is served when it answers — no restart"
  docker stop -t 10 "$container" >/dev/null; echo "the database stopped at $(date +%T)"
  log="$WORK/outage-$engine-start-down.log"
  start_service "$engine" "$log"
  grep -q "could NOT be served" "$log" && echo "the service says: $(grep -m1 "could NOT be served" "$log" | sed 's/.*tenants: //' | cut -c1-140)" || { echo "FAILED: the start did not say the schema could not be served"; grep -E "ERROR|REFUS|NOT STARTED" "$log" | tail -4 | cut -c1-200; verdict=1; }
  docker start "$container" >/dev/null
  for _ in $(seq 1 180); do answers "$engine" && break; sleep 0.5; done
  local back2; back2=$(date +%s); echo "the database answers again at $(date +%T)"
  for _ in $(seq 1 240); do grep -q "is served: 6 of 6" "$log" && break; sleep 0.5; done
  grep -q "is served: 6 of 6" "$log" && echo "served $(( $(date +%s) - back2 )) s after the database answered (the watcher's retry; pid $service_pid, never restarted)" || { echo "FAILED: not served within 120 s of the database's return"; verdict=1; }
  if [ "$engine" = mysql ]; then for _ in $(seq 1 60); do [ -n "$(myv "show tables in $SCHEMA like 'summary_offset'")" ] && break; sleep 0.5; done; fi
  write_rows "$engine" 30
  waitEqual "$engine" 60 || verdict=1
  echo "ERROR lines of this start: $(errorLines "$log") (the one 'could NOT be served')"
  stop_service

  [ "$verdict" = 0 ] && echo "$engine HOLDS: (a) ended sessions, (b) a restarted database, (c) a start while down — every row summed with no restart, the ERROR lines stopped" \
                     || echo "$engine DOES NOT HOLD — see above (logs: $WORK/outage-$engine*.log)"
  return "$verdict"
}

result=0
case "$ENGINES" in
  pg)    story pg || result=1 ;;
  mysql) story mysql || result=1 ;;
  both)  story pg || result=1; cleanup; story mysql || result=1 ;;
  *)     echo "usage: $0 [pg | mysql | both]"; exit 2 ;;
esac
echo; [ "$result" = 0 ] && echo "S16 HOLDS on $ENGINES: the store ended every session and came back; the service caught up by itself, with no restart." || echo "S16 DOES NOT HOLD — see above."
echo "removing: the service, the schema / database (the containers stay)"
exit "$result"
