#!/usr/bin/env bash
# Brief S12 on summary-service's side, with the PACKAGED jar: what a ping topic that DOES NOT EXIST costs, and
# that the service picks it up, with no restart, when it is made.
#
#   tools/lab/ping-topic-e2e.sh
#
# On a deployment the ping's topic carries the root — cdr_summary_ping_<root>, the same name on billing-core's
# side (billing.summary.ping-topic) — and it must EXIST: a deployment's broker makes no topic by itself. This
# story runs on a broker of its own with auto-create OFF (ss-kafka-noauto-lab, 127.0.0.1:7694; made and removed
# here), and sets the poll to 10 minutes so that only a ping can bring a row into the summary:
#   1. the topic is not there: the service starts and serves; it says so in WARN lines; it does not hear
#   2. billing-core writes a view: it is NOT summed (it would wait for the poll: summary.outbox.poll-interval-seconds)
#   3. the topic is made: the listener hears it without a restart, looks once, and the view is summed
#   4. a second view and its ping: summed at once
set -euo pipefail
cd "$(dirname "$0")/../.."

PG=ss-pg16-lab; KA=ss-kafka-noauto-lab; KA_PORT=7694; KA_CTRL=7695
SCHEMA=lab_ping; TOPIC=cdr_summary_ping_btcl
WORK=target/lab-e2e; JAR=target/quarkus-app/quarkus-run.jar
mkdir -p "$WORK"
[ -f "$JAR" ] || { echo "no packaged application — run: mvn package -DskipTests"; exit 2; }
LOG="$WORK/ping-topic.log"

super() { docker exec -i "$PG" psql -U postgres -d routesphere -q -v ON_ERROR_STOP=1 "$@"; }
as()    { local role=$1; shift; docker exec -i "$PG" psql -U "$role" -d routesphere -q -v ON_ERROR_STOP=1 "$@"; }
say()   { printf '\n== %s ==\n' "$*"; }
views() { as summary_service -tA -c "select coalesce(sum(views),0) from $SCHEMA.sum_ad_day_30" 2>/dev/null || echo "?"; }
kt()    { docker exec "$KA" /opt/kafka/bin/kafka-topics.sh --bootstrap-server "127.0.0.1:$KA_PORT" "$@"; }
service_pid=""
cleanup() {
  [ -n "$service_pid" ] && kill "$service_pid" 2>/dev/null || true
  docker rm -f -v "$KA" >/dev/null 2>&1 || true        # -v: its anonymous volumes go with it
  super -c "DROP SCHEMA IF EXISTS $SCHEMA CASCADE" 2>/dev/null || true
}
trap cleanup EXIT
cleanup

say "the lab: a broker that makes NO topic by itself, a schema with billing-core's outbox"
tools/lab/pg-lab.sh up >/dev/null 2>&1 || { echo "the lab's PostgreSQL did not come up: tools/lab/pg-lab.sh up"; exit 1; }
docker run -d --name "$KA" -p 127.0.0.1:${KA_PORT}:${KA_PORT} -e KAFKA_NODE_ID=1 -e KAFKA_PROCESS_ROLES=broker,controller \
  -e KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:${KA_PORT},CONTROLLER://localhost:${KA_CTRL} \
  -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:${KA_PORT} -e KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER \
  -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT \
  -e KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:${KA_CTRL} -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
  -e KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1 -e KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1 \
  -e KAFKA_AUTO_CREATE_TOPICS_ENABLE=false apache/kafka:3.9.0 >/dev/null
for _ in $(seq 1 60); do kt --list >/dev/null 2>&1 && break; sleep 1; done
echo "broker 127.0.0.1:$KA_PORT, auto-create off; its topics: [$(kt --list | grep -v '^__' | tr '\n' ' ')]"
as prime_context -c "CREATE SCHEMA $SCHEMA" -c "GRANT USAGE, CREATE ON SCHEMA $SCHEMA TO summary_service, billing_core"
as billing_core <<SQL
SET search_path TO $SCHEMA;
CREATE TABLE summary_affected (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, entity_type varchar(32) NOT NULL,
  op varchar(8) NOT NULL DEFAULT 'add' CHECK (op IN ('add', 'subtract')), data text NOT NULL);
GRANT SELECT, DELETE ON summary_affected TO summary_service;
SQL
[ -s "$WORK/cp.txt" ] || mvn -o -q dependency:build-classpath -Dmdep.outputFile="$WORK/cp.txt" -Dmdep.includeScope=test >/dev/null
row=$(java -cp "target/classes:target/test-classes:$(cat "$WORK/cp.txt")" com.telcobright.summary.testkit.LabOutboxRow 2>/dev/null)
billing_writes_a_view() { printf "INSERT INTO %s.summary_affected (entity_type, op, data) VALUES ('cdr', 'add', '%s');\n" "$SCHEMA" "$row" | as billing_core; }

say "1 · the topic $TOPIC is not there"
tools/lab/run-lab.sh btcl/lab -Dsummary.tenants.mode=single "-Dsummary.store.url=jdbc:postgresql://127.0.0.1:7643/routesphere?currentSchema=$SCHEMA" \
    "-Dsummary.outbox.ping-bootstrap-servers=127.0.0.1:$KA_PORT" -Dsummary.outbox.poll-interval-seconds=600 > "$LOG" 2>&1 &
service_pid=$!
for _ in $(seq 1 120); do grep -q "is served\|NOT STARTED\|REFUSING" "$LOG" && break; sleep 0.5; done
grep -m1 -o "ENDPOINT ping-kafka .*" "$LOG"
grep -m1 -o "schema (the connection's own) is served: [0-9]* of [0-9]* bean(s) running" "$LOG" || { echo "FAILED: not served:"; tail -15 "$LOG"; exit 1; }
sleep 10
echo "health: $(curl -s -m 3 http://127.0.0.1:7671/q/health | tr -d ' \n' | cut -c1-60)"
echo "WARN lines of the Kafka client that name the missing topic, in the first 10 s: $(grep -c "$TOPIC=UNKNOWN_TOPIC_OR_PARTITION" "$LOG" || true) (about one a second, until the topic is there)"
echo "   $(grep -m1 -o "The metadata response.*UNKNOWN_TOPIC_OR_PARTITION}" "$LOG" | cut -c1-170)"
if grep -q "ping listener is hearing" "$LOG"; then echo "FAILED: it says it hears a topic that is not there"; exit 1; fi
if grep -q "ping listener stopped" "$LOG"; then echo "FAILED: the listener gave up"; exit 1; fi
echo "the service is up and serves; the listener waits for the topic; it has not given up"

say "2 · billing-core writes a view — no ping can reach the service"
billing_writes_a_view
sleep 6
echo "views in $SCHEMA.sum_ad_day_30 after 6 s: $(views)   (the poll would bring it in: it is set to 600 s here, 5 s by default)"
[ "$(views)" = "0" ] || { echo "FAILED: the view was summed without a ping and without the poll"; exit 1; }

say "3 · the topic is made — no restart"
made=$(date +%s.%N)
kt --create --topic "$TOPIC" --partitions 1 --replication-factor 1 >/dev/null
for _ in $(seq 1 600); do grep -q "ping listener is hearing $TOPIC" "$LOG" && break; sleep 0.1; done
grep -m1 -o "ping listener is hearing $TOPIC[^\"]*" "$LOG" || { echo "FAILED: the listener never heard the topic:"; tail -8 "$LOG"; exit 1; }
for _ in $(seq 1 100); do [ "$(views)" = "1" ] && break; sleep 0.1; done
echo "views: $(views), $(echo "$(date +%s.%N) - $made" | bc | cut -c1-5) s after the topic was made (the listener looks once when it can hear)"
[ "$(views)" = "1" ] || { echo "FAILED: the view was not summed"; exit 1; }

say "4 · a second view, and its ping"
billing_writes_a_view
pinged=$(date +%s.%N)
printf '{"tenant":"%s","entity":"cdr","rows":1}\n' "$SCHEMA" | docker exec -i "$KA" /opt/kafka/bin/kafka-console-producer.sh --bootstrap-server "127.0.0.1:$KA_PORT" --topic "$TOPIC" >/dev/null 2>&1
for _ in $(seq 1 100); do [ "$(views)" = "2" ] && break; sleep 0.1; done
echo "views: $(views), within $(echo "$(date +%s.%N) - $pinged" | bc | cut -c1-5) s of sending the ping (the producer's own start included)"
[ "$(views)" = "2" ] || { echo "FAILED: the ping did not bring the view in"; exit 1; }

echo; echo "S12 on this side: without its topic the service runs on the poll alone and says so; made later, the topic is heard with no restart."
echo "removing: the broker $KA, the schema $SCHEMA"
