#!/usr/bin/env bash
# Brief S9 from end to end, with the PACKAGED jar: the store's password is in the service's ENVIRONMENT and nowhere else.
#
#   tools/lab/secret-e2e.sh
#
# The lab's roles are trusted (no password exists). This story needs ONE role that really needs a password, so it
# makes it and removes it again: ss_secret_lab, scram-sha-256, by a pg_hba line of its own in MY container.
# Its password is made here at random and lives in this script's environment only — never in a file, a URL or a
# command line: it reaches PostgreSQL through psql's standard input and the service through the inherited environment.
# The profile only NAMES the variable:   summary.store.password-ref: env:SS_LAB_STORE_PASSWORD
#
#   1. the variable is NOT in the environment -> the start is refused, in words that name the variable; nothing is dialled
#   2. the variable holds a WRONG value       -> the service starts, the store refuses it, it is tried again; nothing is served
#   3. the variable holds the password        -> the schema is served and a view billing-core wrote is summed
#   and the value is nowhere: not in the service's log, not on its command line.
set -euo pipefail
cd "$(dirname "$0")/../.."

PG=ss-pg16-lab
ROLE=ss_secret_lab
SCHEMA=lab_secret
HBA=/var/lib/postgresql/data/pg_hba.conf
WORK=target/lab-e2e
JAR=target/quarkus-app/quarkus-run.jar
mkdir -p "$WORK"
[ -f "$JAR" ] || { echo "no packaged application — run: mvn package -DskipTests"; exit 2; }

super() { docker exec -i "$PG" psql -U postgres -d routesphere -q -v ON_ERROR_STOP=1 "$@"; }
as()    { local role=$1; shift; docker exec -i "$PG" psql -U "$role" -d routesphere -q -v ON_ERROR_STOP=1 "$@"; }
say()   { printf '\n== %s ==\n' "$*"; }
service_pid=""
stop_service() { [ -n "$service_pid" ] && kill "$service_pid" 2>/dev/null || true; service_pid=""; sleep 1; }
cleanup() {
  stop_service
  super -c "DROP SCHEMA IF EXISTS $SCHEMA CASCADE" 2>/dev/null || true
  super -c "DROP ROLE IF EXISTS $ROLE" 2>/dev/null || true
  docker exec "$PG" sed -i "/ $ROLE /d" "$HBA" 2>/dev/null || true
  super -c "select pg_reload_conf()" >/dev/null 2>&1 || true
}
trap cleanup EXIT
cleanup

OPTIONS=(-Dsummary.tenants.mode=single "-Dsummary.store.url=jdbc:postgresql://127.0.0.1:7643/routesphere?currentSchema=$SCHEMA"
         -Dsummary.store.username=$ROLE -Dsummary.store.password-ref=env:SS_LAB_STORE_PASSWORD
         -Dsummary.store.acquisition-timeout-seconds=3 -Dsummary.tenants.retry-seconds=2 -Dsummary.outbox.poll-interval-seconds=1)

say "the lab: a role that NEEDS a password, a schema of its own, billing-core's outbox in it"
PASSWORD=$(head -c 18 /dev/urandom | od -An -tx1 | tr -d ' \n')          # the value is never an argument of any command
WRONG=$(head -c 18 /dev/urandom | od -An -tx1 | tr -d ' \n')
super -c "CREATE ROLE $ROLE LOGIN"
printf "ALTER ROLE %s PASSWORD '%s';\n" "$ROLE" "$PASSWORD" | super                # through standard input
docker exec "$PG" sed -i "1i host all $ROLE all scram-sha-256" "$HBA"
super -c "select pg_reload_conf()" >/dev/null
as prime_context -c "CREATE SCHEMA $SCHEMA" -c "GRANT USAGE, CREATE ON SCHEMA $SCHEMA TO $ROLE, billing_core"
as billing_core <<SQL
SET search_path TO $SCHEMA;
CREATE TABLE summary_affected (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, entity_type varchar(32) NOT NULL,
  op varchar(8) NOT NULL DEFAULT 'add' CHECK (op IN ('add', 'subtract')), data text NOT NULL);
GRANT SELECT, DELETE ON summary_affected TO $ROLE;
SQL
echo "role $ROLE: $(docker exec "$PG" sed -n "1p" "$HBA")   (every other role of the lab: trust)"

say "1 · the variable is NOT in the environment"
set +e
env -u SS_LAB_STORE_PASSWORD tools/lab/run-lab.sh --show btcl/lab "${OPTIONS[@]}" > "$WORK/secret-1-show.log" 2>&1; shown=$?
# the service's own refusal, without the script's check in front of it (the endpoints above are all this machine)
env -u SS_LAB_STORE_PASSWORD java -Dsummary.active-tenant=btcl/lab -Dquarkus.http.host=127.0.0.1 -Dquarkus.http.port=7671 "${OPTIONS[@]}" \
    -Dsummary.endpoints.loopback-only=true -Dsummary.autostart=true -jar "$JAR" > "$WORK/secret-1-start.log" 2>&1; started=$?
set -e
grep -E "^ENDPOINT|^SECRET|^== " "$WORK/secret-1-show.log" | cut -c1-230
echo "run-lab.sh --show exit code: $shown (4 = the named variable is not set)"
echo "the service's own start: exit code $started; it said:"
grep -m1 -o "REFUSING TO START: the environment variable [A-Z_]* is not set[^\"]*" "$WORK/secret-1-start.log" | cut -c1-260
[ "$shown" = "4" ] && [ "$started" != "0" ] || { echo "FAILED: a start without the variable was not refused"; exit 1; }
if grep -qE "store: postgresql|worker started|is served" "$WORK/secret-1-start.log"; then echo "FAILED: something was dialled or started"; exit 1; fi
echo "nothing was dialled: no pool was made, no worker started"

start_service() {   # $1 = the value the variable holds for this start, $2 = the log
  SS_LAB_STORE_PASSWORD="$1" tools/lab/run-lab.sh btcl/lab "${OPTIONS[@]}" > "$2" 2>&1 &
  service_pid=$!
  for _ in $(seq 1 120); do grep -q "started in\|NOT STARTED\|REFUSING" "$2" && break; sleep 0.5; done
  grep -q "started in" "$2" || { echo "the service did not start:"; tail -15 "$2"; exit 1; }
}
nowhere() {   # the value is not in the log and not on the command line (asked with shell built-ins: the value is no command's argument)
  local log; log=$(cat "$2"); local cmd=""
  for pid in $(pgrep -f "active-tenant=btcl/lab" || true); do cmd="$cmd $(tr '\0' ' ' < /proc/$pid/cmdline 2>/dev/null || true)"; done
  [[ "$log" != *"$1"* ]] || { echo "FAILED: the value is in the log $2"; exit 1; }
  [[ "$cmd" != *"$1"* ]] || { echo "FAILED: the value is on a command line"; exit 1; }
  echo "the value is not in the service's log and not on its command line"
}

say "2 · the variable holds a WRONG value"
start_service "$WRONG" "$WORK/secret-2.log"
grep -E "^SECRET" "$WORK/secret-2.log" | cut -c1-200
for _ in $(seq 1 60); do grep -q "password authentication failed" "$WORK/secret-2.log" && break; sleep 0.5; done
grep -m1 -o "password authentication failed for user \"$ROLE\"" "$WORK/secret-2.log" || { echo "FAILED: the store did not refuse the wrong value:"; tail -15 "$WORK/secret-2.log"; exit 1; }
sleep 5
tries=$(grep -c "could NOT be served" "$WORK/secret-2.log" || true)
echo "the store refused it; the service stays up and tried $tries times so far; served: $(grep -c 'is served' "$WORK/secret-2.log" || true) schema(s)"
[ "$tries" -ge 2 ] || { echo "FAILED: it was not tried again"; exit 1; }
if grep -q "worker started" "$WORK/secret-2.log"; then echo "FAILED: a worker started with a wrong password"; exit 1; fi
nowhere "$WRONG" "$WORK/secret-2.log"
stop_service

say "3 · the variable holds the password"
start_service "$PASSWORD" "$WORK/secret-3.log"
grep -E "^SECRET" "$WORK/secret-3.log" | cut -c1-200
grep -m1 -o "the store's password: from the environment variable [A-Z_]* (summary.store.password-ref)" "$WORK/secret-3.log"
for _ in $(seq 1 60); do grep -q "is served" "$WORK/secret-3.log" && break; sleep 0.5; done
grep -m1 -o "schema (the connection's own) is served: [0-9]* of [0-9]* bean(s) running" "$WORK/secret-3.log" || { echo "FAILED: not served:"; tail -15 "$WORK/secret-3.log"; exit 1; }
[ -s "$WORK/cp.txt" ] || mvn -o -q dependency:build-classpath -Dmdep.outputFile="$WORK/cp.txt" -Dmdep.includeScope=test >/dev/null
row=$(java -cp "target/classes:target/test-classes:$(cat "$WORK/cp.txt")" com.telcobright.summary.testkit.LabOutboxRow 2>/dev/null)
printf "INSERT INTO %s.summary_affected (entity_type, op, data) VALUES ('cdr', 'add', '%s');\n" "$SCHEMA" "$row" | as billing_core
for _ in $(seq 1 60); do [ "$(as $ROLE -tA -c "select coalesce(sum(views),0) from $SCHEMA.sum_ad_day_30" 2>/dev/null || echo 0)" = "1" ] && break; sleep 0.5; done
echo "a view billing-core wrote is summed: $(as $ROLE -tA -c "select concat_ws(' | ', tup_tenant, 'views ' || views, 'money ' || chargedamount) from $SCHEMA.sum_ad_day_30")"
[ "$(as $ROLE -tA -c "select coalesce(sum(views),0) from $SCHEMA.sum_ad_day_30")" = "1" ] || { echo "FAILED: the view was not summed"; exit 1; }
nowhere "$PASSWORD" "$WORK/secret-3.log"
stop_service

echo; echo "S9 HOLDS: refused without the variable, refused by the store with a wrong one, served with the right one; the value is nowhere but the environment."
echo "removing: the role, its pg_hba line, the schema"
