-- =====================================================================================
-- sum_ad_day_30 / sum_ad_hr_30 on PostgreSQL — the ad summary (service group 30).
--
-- ONE PAIR PER TIER SCHEMA of the switch database (ad-is-a-call §3: a tenant is a schema —
-- btcl, res_44, res_44_7). summary-service (role summary_service) creates them at first use
-- in the schema it serves; nobody else writes them. ad-sphere reads them
-- (JdbcCdrReader.summary: SELECT … FROM <tier>.sum_ad_day_30 | sum_ad_hr_30).
--
-- This file is the reference copy. From S5 on the service renders the same tables itself
-- at first use; a test keeps this file and the rendered DDL equal, column for column.
--
--   * the columns are AdSummary.INSERT_COLUMNS — the same names and order as on MySQL;
--   * what a tier was charged is TWO measures, never added: chargedamount is MONEY (the charges
--     whose unit is BDT), chargedunits is what was paid in a package's units (ruled on SS-0001);
--   * tup_tenant is ALWAYS the schema's own name (one pair per tier now);
--   * tup_app is 64 wide (it was 32; ad-sphere's app name is 64);
--   * tup_starttime is TIMESTAMP WITHOUT TIME ZONE: the TENANT's wall clock (Asia/Dhaka),
--     the window's start — the day at 00:00:00, the hour at HH:00:00. Never the JVM's zone;
--   * unquoted identifiers, so PostgreSQL stores them in lower case;
--   * a PLAIN table, not partitioned (ruled on SS-0001: a summary table holds one row per key
--     per day or hour; there is no partitioned form on PostgreSQL). MySQL keeps its partitions.
--
-- Rights (prime-context's provisioning, R5): summary_service has USAGE + CREATE on the tier
-- schema and owns these tables; ad_sphere reads them through
--   ALTER DEFAULT PRIVILEGES FOR ROLE summary_service IN SCHEMA <tier> GRANT SELECT ON TABLES TO ad_sphere
-- =====================================================================================

CREATE TABLE IF NOT EXISTS sum_ad_day_30 (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tup_tenant     VARCHAR(100)  NOT NULL DEFAULT '',   -- the tier = the schema's own name
    tup_partnerid  INTEGER       NOT NULL DEFAULT 0,    -- cdr.InPartnerId: this tier's payer
    tup_campaignid INTEGER       NOT NULL DEFAULT 0,    -- AdditionalMetaData.campaignId (0 = none)
    tup_rulecode   VARCHAR(20)   NOT NULL DEFAULT '',   -- cdr.OriginatingCalledNumber
    tup_zone       VARCHAR(64)   NOT NULL DEFAULT '',   -- AdditionalMetaData.zone
    tup_site       VARCHAR(64)   NOT NULL DEFAULT '',   -- AdditionalMetaData.site
    tup_app        VARCHAR(64)   NOT NULL DEFAULT '',   -- AdditionalMetaData.app
    tup_mediakind  VARCHAR(16)   NOT NULL DEFAULT '',   -- cdr.Codec
    tup_outcome    VARCHAR(32)   NOT NULL DEFAULT '',   -- done (HangupCause NORMAL_CLEARING) | failed
    tup_starttime  TIMESTAMP     NOT NULL,              -- the day's start, the tenant's wall clock
    views          BIGINT        NOT NULL DEFAULT 0,
    shown          BIGINT        NOT NULL DEFAULT 0,    -- an answer time
    completed      BIGINT        NOT NULL DEFAULT 0,    -- AdditionalMetaData.completed
    credited       BIGINT        NOT NULL DEFAULT 0,    -- AdditionalMetaData.credited
    failed         BIGINT        NOT NULL DEFAULT 0,
    watchedsec     BIGINT        NOT NULL DEFAULT 0,    -- cdr.DurationSec
    chargedamount  NUMERIC(18,6) NOT NULL DEFAULT 0,    -- MONEY: the customer chargeable's BilledAmount when its unit is BDT
    chargedunits   NUMERIC(18,6) NOT NULL DEFAULT 0,    -- UNITS: the same amount when the tier paid from a package
    PRIMARY KEY (id, tup_starttime)
);
CREATE INDEX IF NOT EXISTS sum_ad_day_30_ix_starttime ON sum_ad_day_30 (tup_starttime);
CREATE INDEX IF NOT EXISTS sum_ad_day_30_ix_tenant_partner ON sum_ad_day_30 (tup_tenant, tup_partnerid, tup_starttime);

CREATE TABLE IF NOT EXISTS sum_ad_hr_30 (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tup_tenant     VARCHAR(100)  NOT NULL DEFAULT '',
    tup_partnerid  INTEGER       NOT NULL DEFAULT 0,
    tup_campaignid INTEGER       NOT NULL DEFAULT 0,
    tup_rulecode   VARCHAR(20)   NOT NULL DEFAULT '',
    tup_zone       VARCHAR(64)   NOT NULL DEFAULT '',
    tup_site       VARCHAR(64)   NOT NULL DEFAULT '',
    tup_app        VARCHAR(64)   NOT NULL DEFAULT '',
    tup_mediakind  VARCHAR(16)   NOT NULL DEFAULT '',
    tup_outcome    VARCHAR(32)   NOT NULL DEFAULT '',
    tup_starttime  TIMESTAMP     NOT NULL,              -- the hour's start, the tenant's wall clock
    views          BIGINT        NOT NULL DEFAULT 0,
    shown          BIGINT        NOT NULL DEFAULT 0,
    completed      BIGINT        NOT NULL DEFAULT 0,
    credited       BIGINT        NOT NULL DEFAULT 0,
    failed         BIGINT        NOT NULL DEFAULT 0,
    watchedsec     BIGINT        NOT NULL DEFAULT 0,
    chargedamount  NUMERIC(18,6) NOT NULL DEFAULT 0,
    chargedunits   NUMERIC(18,6) NOT NULL DEFAULT 0,
    PRIMARY KEY (id, tup_starttime)
);
CREATE INDEX IF NOT EXISTS sum_ad_hr_30_ix_starttime ON sum_ad_hr_30 (tup_starttime);
CREATE INDEX IF NOT EXISTS sum_ad_hr_30_ix_tenant_partner ON sum_ad_hr_30 (tup_tenant, tup_partnerid, tup_starttime);
